### ISSUE TITLE
Add support for idempotent requests..

### ISSUE THREAD

**Issue by ibrierley** [aquaron/Business-Stripe#22]
Stripe can support Idempotent requests, i.e https://stripe.com/docs/api/idempotent_requests

I was looking at maybe adding this, but I'm wondering about best place in the code for it to hang (that's if its wanted). As it needs to turn into a header, the current header code looks for the Stripe objects longer term api credentials and things like that, but I guess someone may want to add idempotency for a charge, but not something else, so feels like it has to be a per call addition.

We could add an add_headers(hashref) method which gets stored in $self->{headers}, adds them in _compose to @headers, then undeffed  ? Any other thoughts ?

**Comment by garu** [comment]
Hi @ibrierley! I've made #23 to support setting dynamic headers via _-dashed_arguments_ (which are not allowed on Stripe's API), and even included support for "-idempotency_key". The way I did it was by refactoring `api()` to do all the heavy lifting (even `_compose()` now uses it instead of the other way around). Could you please take a look and comment on the PR if it looks ok? If I merge it to master, then any and all calls to `api()` can include custom headers, like so:

```perl
   $stripe->api('get', 'subscribers', -idempotency_key => 123, -version => '2017-04-06');
```
This means that all we have to do (after the merge) is refactor all methods to use `api()` instead of `_compose()`, which should be simple enough.

What do you think?

**Comment by ibrierley** [comment]
Works great for me, returns the same id's each time if I include the -idempotency_key, so I think that's all fine! Many thanks.
