### ISSUE TITLE
add helpers for Stripe's Payment Intent endpoints (EU regulation)

### ISSUE THREAD

**Issue by ibrierley** [aquaron/Business-Stripe#7]
Hi, my understanding is that Stripe will be changing and using things like payment intents (e.g https://stripe.com/docs/payments/payment-intents ) to support SCA (Strong Customer Authentication) https://stripe.com/docs/strong-customer-authentication/migration#sca-updates

I'm a little confused as to whether Business::Stripe will continue to work.

Does anyone know if it will continue to work and be unaffected, or whether there will need to be some code changes ?

**Comment by garu** [comment]
Hi! Don't worry: SCA will be *recommended* (not required) after 2019-09-14, and (at least for now) only to EU customers sending or receiving payments. Those who do not use it *may* see more declined payments after that date. Stripe will **not** deprecate its current API so this module should continue to work without any glitches.

The new SCA endpoints are already available and the change is actually quite minimal: as per their documentation (which you have linked to already), if you wish to update your payment flow to comply with SCA, all you have to do is:

1. update your calls to use `$stripe->api("payment_intents", \%params)` endpoints (instead of calling `$stripe->charges_create(\%params)`);

2. update your client-side `Stripe.js`, and set up a new webhook endpoint (or cron job) where you will get any extra validation data and either complete or deny the payment. 

3. Accept that the response from Stripe.js will not be final (as it's already the case, sometimes, when payment processing is delayed for fraud analysis or whatever reason) and you'll need to check again at a later time, either listening on a webhook or querying through a cron job (see step 2 above).

That said, a new version of Business::Stripe providing a helper method for payment intents would be nice :)

Hope this helps! Cheers!

**Comment by garu** [comment]
Isn't it great when developers take matters into their own hands? Thank you very much for your patch on #21!
